"""Yarimono Archipelago items.

Item Categories:

- TRAINER_LEVEL: Each one increases the max trainer level by one.
- EVENT_ITEM: Items that grant access to new scenes.
- ULTIMATE_MOVE: Unlocks access to ultimate moves for each type.
- SCENE_UNLOCK: Unlocks access to scenes in the Yariman Encyclopedia.
- JUNK: Consumables and White Fluff.

"""

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum, auto

from BaseClasses import Item, ItemClassification

BASE_ID = 1082_000
EVENT_ITEM_BASE_ID = BASE_ID + 1000
JUNK_BASE_ID = BASE_ID + 2000
ULTIMATE_MOVE_BASE_ID = BASE_ID + 3000
SCENE_UNLOCK_BASE_ID = BASE_ID + 4000
GOLD_BASE_ID = BASE_ID + 5000


class ItemCategory(IntEnum):
    TRAINER_LEVEL = auto()
    EVENT_ITEM = auto()
    ULTIMATE_MOVE = auto()
    SCENE_UNLOCK = auto()
    JUNK = auto()
    GOLD = auto()


@dataclass(frozen=True)
class ItemDef:
    code: int  # unique numeric AP item id
    name: str  # AP item name shown to the player
    category: ItemCategory
    classification: ItemClassification

    @property
    def is_progression(self) -> bool:
        return ItemClassification.progression in self.classification

    def effective_classification(self, scenes_randomized: bool) -> ItemClassification:
        """Resolve the classification used at pool-creation time.

        When "randomize_yariman_encyclopedia" is on, non-filler event items become progression.
        """
        if (scenes_randomized
                and self.category == ItemCategory.EVENT_ITEM
                and self.classification != ItemClassification.filler):
            return ItemClassification.progression
        return self.classification


# ---------------------------------------------------------------------------
# Item table. Add new items here; the world generator reads this directly.
# ---------------------------------------------------------------------------

ITEMS: list[ItemDef] = [
    # --- Main Progression ---
    ItemDef(BASE_ID + 1, "Trainer Level",
            ItemCategory.TRAINER_LEVEL, ItemClassification.progression),

    # --- Event Items ---
    ItemDef(EVENT_ITEM_BASE_ID + 31, "VIP Card",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),
    ItemDef(EVENT_ITEM_BASE_ID + 38, "Super Ball",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),
    # Unlike most event items, this one doesn't grant any events, just modifies an existing one.
    ItemDef(EVENT_ITEM_BASE_ID + 39, "White Fluff",
            ItemCategory.EVENT_ITEM, ItemClassification.filler),
    ItemDef(EVENT_ITEM_BASE_ID + 41, "Book of Shinobi",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),
    ItemDef(EVENT_ITEM_BASE_ID + 42, "Strange Medicine",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),
    ItemDef(EVENT_ITEM_BASE_ID + 43, "Electric Anal Vibe",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),
    ItemDef(EVENT_ITEM_BASE_ID + 44, "Reserved Bath Ticket 1",
            ItemCategory.EVENT_ITEM, ItemClassification.progression),
    ItemDef(EVENT_ITEM_BASE_ID + 45, "Reserved Bath Ticket 2",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),
    ItemDef(EVENT_ITEM_BASE_ID + 46, "Reserved Bath Ticket 3",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),
    ItemDef(EVENT_ITEM_BASE_ID + 47, "Nose Hook",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),
    ItemDef(EVENT_ITEM_BASE_ID + 50, "5000 Yen Swimsuit Voucher 1",
            ItemCategory.EVENT_ITEM, ItemClassification.progression),
    ItemDef(EVENT_ITEM_BASE_ID + 51, "20000 Yen Swimsuit Voucher",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),
    ItemDef(EVENT_ITEM_BASE_ID + 52, "All Swimsuit Voucher",
            ItemCategory.EVENT_ITEM, ItemClassification.progression),
    ItemDef(EVENT_ITEM_BASE_ID + 53, "20000 Yen Swimsuit Voucher Back",
            ItemCategory.EVENT_ITEM, ItemClassification.progression),
    ItemDef(EVENT_ITEM_BASE_ID + 54, "5000 Yen Swimsuit Voucher 2",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),
    ItemDef(EVENT_ITEM_BASE_ID + 56, "Matsutake",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),
    ItemDef(EVENT_ITEM_BASE_ID + 57, "Wonderful Spray",
            ItemCategory.EVENT_ITEM, ItemClassification.useful),

    # --- Consumables ---
    ItemDef(JUNK_BASE_ID + 1, "Recovery Beans", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 2, "Recovery Senbei", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 3, "Rec. Castella", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 4, "Full Tank Soup", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 5, "Foamy Detergent", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 6, "Hog Sheet", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 7, "Bean Paste Cure", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 8, "Energy Mushroom", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 13, "Attack-ola", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 14, "Guardrip", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 15, "Speedy Soda", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 16, "Safe-T", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 17, "Hit Milk", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 20, "Star Disk", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 21, "Repel Incense", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 22, "Super Incense", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 23, "Ultra Incense", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 24, "Bond Star", ItemCategory.JUNK, ItemClassification.filler),
    ItemDef(JUNK_BASE_ID + 25, "Soul Boost", ItemCategory.JUNK, ItemClassification.filler),

    # --- Ultimate Moves ---
    ItemDef(ULTIMATE_MOVE_BASE_ID + 42, "Ultimate Typeless Move", ItemCategory.ULTIMATE_MOVE, ItemClassification.useful),
    ItemDef(ULTIMATE_MOVE_BASE_ID + 43, "Ultimate Fire Move", ItemCategory.ULTIMATE_MOVE, ItemClassification.useful),
    ItemDef(ULTIMATE_MOVE_BASE_ID + 44, "Ultimate Water Move", ItemCategory.ULTIMATE_MOVE, ItemClassification.useful),
    ItemDef(ULTIMATE_MOVE_BASE_ID + 45, "Ultimate Wind Move", ItemCategory.ULTIMATE_MOVE, ItemClassification.useful),
    ItemDef(ULTIMATE_MOVE_BASE_ID + 46, "Ultimate Earth Move", ItemCategory.ULTIMATE_MOVE, ItemClassification.useful),
    ItemDef(ULTIMATE_MOVE_BASE_ID + 47, "Ultimate Light Move", ItemCategory.ULTIMATE_MOVE, ItemClassification.useful),
    ItemDef(ULTIMATE_MOVE_BASE_ID + 48, "Ultimate Dark Move", ItemCategory.ULTIMATE_MOVE, ItemClassification.useful),

    # --- Scene Unlocks ---
    ItemDef(SCENE_UNLOCK_BASE_ID + 0, "Hikari Scene 1 (The First XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 1, "Hikari Scene 2 (Wano Town XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 2, "Hikari Scene 3 (Home XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 3, "Hikari Scene 4 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 4, "Hikari Scene 5 (DLC2 - Small road XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 10, "Leo Scene 1 (Harbor Town Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 11, "Leo Scene 2 (Forest Rest Stop XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 12, "Leo Scene 3 (Pool XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 13, "Leo Scene 4 (DLC1 - Love Chat Meeting)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 14, "Leo Scene 5 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 15, "Leo Scene 6 (I'll also do it!)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 20, "Sanae Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 21, "Sanae Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 30, "Yuna Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 40, "Sumire Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 50, "Hotaru Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 51, "Hotaru Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 60, "Honoka Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 61, "Honoka Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 70, "Riona Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 71, "Riona Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 80, "Natsumi Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 81, "Natsumi Scene 2 (Urine)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 82, "Natsumi Scene 3 (Intimacy)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 90, "Kurumi Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 100, "Meena Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 101, "Meena Scene 2 (DLC2 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 110, "Emily Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 120, "Nene Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 121, "Nene Scene 2 (DLC2 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 130, "Armin Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 140, "Marisa Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 141, "Marisa Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 150, "Murasaki Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 151, "Murasaki Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 160, "Fran Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 170, "Akari Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 180, "Marin Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 190, "Mei Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 200, "Hibana Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 201, "Hibana Scene 2 (What I'm good at)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 210, "Minako Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 211, "Minako Scene 2 (DLC1 - Crime?)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 220, "Tina Scene 1 (Lucky Pervert!)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 221, "Tina Scene 2 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 230, "Tamaki Scene 1 (Lucky Pervert!)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 231, "Tamaki Scene 2 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 240, "Haruka Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 250, "Yume Scene 1 (Secret Hospitality 1)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 251, "Yume Scene 2 (Secret Hospitality 2)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 260, "Kanata Scene 1 (You reap what you sow)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 261, "Kanata Scene 2 (Dance Debut)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 270, "Jill Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 271, "Jill Scene 2 (In the Ruins)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 280, "Melon Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 281, "Melon Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 290, "Marble Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 300, "Kanako Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 301, "Kanako Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 310, "Totoro Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 311, "Totoro Scene 2 (Cultist Welcome)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 312, "Totoro Scene 3 (Anal Ninjutsu)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 320, "Shishio Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 321, "Shishio Scene 2 (Hot Spring Peeping)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 322, "Shishio Scene 3 (DLC2 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 330, "Chie Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 340, "Anna Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 341, "Anna Scene 2 (DLC2 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 350, "Phineh Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 360, "Nanase Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 361, "Nanase Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 370, "Kurohime Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 371, "Kurohime Scene 2 (Mansion 3some)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 380, "Momohime Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 381, "Momohime Scene 2 (Mansion 3some)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 390, "Sofia Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 391, "Sofia Scene 2 (DLC2 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 400, "Murei Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 401, "Murei Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 402, "Murei Scene 3 (DLC1 - Evil Spirits, Begone!)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 410, "Sara Scene 1 (OPPAI!)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 411, "Sara Scene 2 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 412, "Sara Scene 3 (DLC1 - Repaying with your body)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 420, "Aoi Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 421, "Aoi Scene 2 (Pool 3some)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 422, "Aoi Scene 3 (Anal Licking Handjob)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 423, "Aoi Scene 4 (Flirty Love XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 430, "Shiryu Scene 1 (Masturbation)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 431, "Shiryu Scene 2 (Seeing through)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 432, "Shiryu Scene 3 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 440, "Linlin Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 450, "Rumi Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 451, "Rumi Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 460, "Maho Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 461, "Maho Scene 2 (DLC1 - Forceful Kiss)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 470, "Kuina Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 471, "Kuina Scene 2 (DLC1 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 480, "Luna Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 481, "Luna Scene 2 (Masturbation Peeping)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 482, "Luna Scene 3 (Hot Spring XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 483, "Luna Scene 4 (Mother and Daughter 3some)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 484, "Luna Scene 5 (Titjob)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 485, "Luna Scene 6 (Mother and Daughter 3some Pt.2)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 490, "Vritra Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 491, "Vritra Scene 2 (Breast Groping)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 492, "Vritra Scene 3 (Rejuvenation Tricks)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 500, "Maki Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 501, "Maki Scene 2 (Hot Spring XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 502, "Maki Scene 3 (DLC1 - Study Session XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 503, "Maki Scene 4 (DLC2 - Video Shooting)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 510, "Aya Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 511, "Aya Scene 2 (Cultist Beverage)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 512, "Aya Scene 3 (Toilet Mode!)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 513, "Aya Scene 4 (DLC2 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 520, "Iori Scene 1 (Cultist Welcome Performance)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 521, "Iori Scene 2 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 522, "Iori Scene 3 (Iori & Yoru 3some)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 530, "Taiga Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 531, "Taiga Scene 2 (Hot Spring XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 532, "Taiga Scene 3 (DLC2 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 540, "Akira Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 541, "Akira Scene 2 (At the Pool)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 542, "Akira Scene 3 (Masturbation Support)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 543, "Akira Scene 4 (DLC2 - Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 550, "Kana Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 560, "Hina Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 561, "Hina Scene 2 (Conversation in private room)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 570, "Yoru Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 571, "Yoru Scene 2 (Touching...)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 572, "Yoru Scene 3 (I want to serve you!)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 580, "Neru Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 581, "Neru Scene 2 (Must use it...)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 590, "Mizuki Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 591, "Mizuki Scene 2 (Wonderful★Spray)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 600, "Patra Scene 1 (Victory H)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 601, "Patra Scene 2 (Share it!)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 602, "Patra Scene 3 (Hitting it off)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 603, "Patra Scene 4 (Interesting woman)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 610, "Opera Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 620, "Vice Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 630, "Quem Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 640, "Athena Scene 1 (Victory XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 641, "Athena Scene 2 (Pool XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 642, "Athena Scene 3 (Hidden Boob Job)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 643, "Athena Scene 4 (Even with my butt...)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 644, "Athena Scene 5 (Super VIP room)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 650, "Teresa Scene 1 (Boob job Invasion)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 651, "Teresa Scene 2 (Pussy Invasion)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 660, "Flare Scene 1 (Empathetic XXX)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 661, "Flare Scene 2 (With my partner...)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 662, "Flare Scene 3 (DLC1 - Flirting)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 663, "Flare Scene 4 (DLC2 - Lovey-dovey flirting)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 670, "Lisa Scene 1 (Over in 5 minutes)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 680, "Hiroko Scene 1 (The One Who Realizes)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 690, "Ero-doujin Sensei Scene 1 (Ero-doujin sensei!)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 700, "Tama Scene 1 (R18 Physical Examinations)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 710, "Extras Scene 1 (Extracurricular Activities)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 711, "Extras Scene 2 (Fleshlight Committee)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    ItemDef(SCENE_UNLOCK_BASE_ID + 712, "Extras Scene 3 (Don't worry about it)",
            ItemCategory.SCENE_UNLOCK, ItemClassification.filler),
    
    # --- Gold (Yen) ---
    ItemDef(GOLD_BASE_ID + 1, "1000 Yen", ItemCategory.GOLD, ItemClassification.filler),
    ItemDef(GOLD_BASE_ID + 2, "2000 Yen", ItemCategory.GOLD, ItemClassification.filler),
    ItemDef(GOLD_BASE_ID + 5, "5000 Yen", ItemCategory.GOLD, ItemClassification.filler),
    ItemDef(GOLD_BASE_ID + 10, "10000 Yen", ItemCategory.GOLD, ItemClassification.filler),
]

# Convenience lookups
ITEM_BY_NAME: dict[str, ItemDef] = {it.name: it for it in ITEMS}
ITEM_BY_CODE: dict[int, ItemDef] = {it.code: it for it in ITEMS}


class YarimonoItem(Item):
    game = "Yarimono"


def make_item(name: str, player: int, scenes_randomized: bool = False) -> YarimonoItem:
    d = ITEM_BY_NAME[name]
    return YarimonoItem(d.name, d.effective_classification(scenes_randomized), d.code, player)
